spring.application.name=spring-data-mongodb
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=testEmpDB

logging.level.org.springframework.data=debug
logging.level.=error
